### ISSUE TITLE
Fix documentation issue per CocoaPods

### ISSUE THREAD

**Issue by fulldecent** [fulldecent/FDWaveformView#87]
According to CocoaPods, our documentation is deficient.

Evidence: https://travis-ci.org/fulldecent/FDWaveformView/builds/222183787#L452

# Work plan

- [ ] Identify exactly what causes that metric to fail
- [ ] Update https://github.com/fulldecent/swift3-module-template and https://github.com/fulldecent/swift3-module-template/blob/master/__PROJECT_NAME__/Tests/CheckCocoaPodsQualityIndexes.rb to output said explanation directly into the Travis console output
- [ ] Fix the thing

**Comment by fulldecent** [comment]
This is resolved in the latest release, evidence: https://travis-ci.org/fulldecent/FDWaveformView/builds/517591224#L910
