### ISSUE TITLE
Add the required number of tests [HELP WANTED]

### ISSUE THREAD

**Issue by fulldecent** [fulldecent/FDWaveformView#88]
According to CocoaPods, our testing is deficient.

Evidence: https://travis-ci.org/fulldecent/FDWaveformView/builds/222183787#L466

# Work plan

- [ ] Identify exactly what causes that metric to fail
- [ ] Update https://github.com/fulldecent/swift3-module-template and https://github.com/fulldecent/swift3-module-template/blob/master/__PROJECT_NAME__/Tests/CheckCocoaPodsQualityIndexes.rb to output said explanation directly into the Travis console output
- [ ] Fix the thing

**Comment by fulldecent** [comment]
Removed CocoaPods
